dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./cmd/otelcol-dev
  otelcol_version: 0.73.0

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/loggingexporter v0.73.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/jaegerexporter
      v0.73.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.73.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.73.0
  - gomod: github.com/imp20052904/otel-collector-dev/receiver/tailtracer v0.1.0

replaces:
  - github.com/imp20052904/otel-collector-dev/receiver/tailtracer => ../../receiver/tailtracer
