receivers:
  otlp:
    protocols:
      grpc:
  tailtracer: # this line represents the ID of your receiver
    interval: 15s
    number_of_traces: 1

processors:
  batch:

exporters:
  logging:
    verbosity: detailed
  jaeger:
    endpoint: localhost:14250
    tls:
      insecure: true

extensions:
  zpages:
    endpoint: :55679

service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [otlp, tailtracer]
      processors: [batch]
      exporters: [jaeger, logging]
  telemetry:
    logs:
      level: info